export default defineEventHandler(() => {
  return {
    tasks: [
      {
        id: "a",
        title: "Test task 1",
        description: "A completed task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: true,
        isReady: true,
      },
      {
        id: "b",
        title: "1234567890 2345678901234567890",
        description: "A ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: true,
      },
      {
        id: "c",
        title: "Test task 3",
        description: "A not ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: false,
      },
      {
        id: "a",
        title: "Test task 1",
        description: "A completed task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: true,
        isReady: true,
      },
      {
        id: "b",
        title: "Test task 2",
        description: "A ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: true,
      },
      {
        id: "c",
        title: "Test task 3",
        description: "A not ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: false,
      },

      {
        id: "a",
        title: "Test task 1",
        description: "A completed task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: true,
        isReady: true,
      },
      {
        id: "b",
        title: "Test task 2",
        description: "A ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: true,
      },
      {
        id: "c",
        title: "Test task 3",
        description: "A not ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: false,
      },
      {
        id: "a",
        title: "Test task 1",
        description: "A completed task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: true,
        isReady: true,
      },
      {
        id: "b",
        title: "Test task 2",
        description: "A ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: true,
      },
      {
        id: "c",
        title: "Test task 3",
        description: "A not ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: false,
      },
      {
        id: "a",
        title: "Test task 1",
        description: "A completed task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: true,
        isReady: true,
      },
      {
        id: "b",
        title: "Test task 2",
        description: "A ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: true,
      },
      {
        id: "c",
        title: "Test task 3",
        description: "A not ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: false,
      },
      {
        id: "a",
        title: "Test task 1",
        description: "A completed task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: true,
        isReady: true,
      },
      {
        id: "b",
        title: "Test task 2",
        description: "A ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: true,
      },
      {
        id: "c",
        title: "Test task 3",
        description: "A not ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: false,
      },
      {
        id: "a",
        title: "Test task 1",
        description: "A completed task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: true,
        isReady: true,
      },
      {
        id: "b",
        title: "Test task 2",
        description: "A ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: true,
      },
      {
        id: "c",
        title: "Test task 3",
        description: "A not ready task for testing! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac fermentum dui. Nam dapibus, nisi eu pretium lacinia, purus massa semper orci, porttitor egestas ipsum velit a erat. Etiam molestie pretium tortor, vel blandit neque. Donec eget porta felis. Sed et turpis ipsum. Fusce pharetra rutrum elit, et semper orci sollicitudin sed. Mauris tempor ligula quis eros sodales, non rutrum nisi lacinia.",
        isComplete: false,
        isReady: false,
      },
    ]
  }
})