// Generated by Wrangler by running `wrangler types`

interface Env {
	CF_DB: D1Database;

	// secrets
	NUXT_OAUTH_GITHUB_CLIENT_ID: string;
	NUXT_OAUTH_GITHUB_CLIENT_SECRET: string;
	NUXT_SESSION_PASSWORD: string
}
